name: Test Beacon Prospecta

on:
  workflow_dispatch:

jobs:
  prospecta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: Run Prospecta
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python beacon.py
